# ESLint is pluggable and configurable linter tool for identifying
# and reporting problematic patterns found in JavaScript code.
# © ESLint <https://eslint.org>
---
# Parser to generate AST.
parser: '@typescript-eslint/parser'

# Language specification.
parserOptions:
  ecmaVersion: 2018
  sourceType: module

# External plugins.
extends:
  - plugin:jest/recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended

# Rules configuration.
rules:
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/no-explicit-any': 'off'

# Override rules for matched files.
overrides:
  - files:
      - '**/testing/**/*.ts'

    rules:
      '@typescript-eslint/no-unused-vars': 'off'
      '@typescript-eslint/explicit-function-return-type': 'off'
...
