# Prettier enforces a consistent code style across entire codebase because it
# disregards the original styling by parsing it away and re-printing the parsed
# AST with its own rules that take the maximum line length into account, wrapping
# code when necessary.
# © Prettier <https://prettier.io>

# The line length that the Printer will wrap on.
printWidth: 120

# Use single quotes instead of double quotes.
singleQuote: true
