language:
  node_js

node_js:
  node

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

script:
  - set -e

  - echo 'Checking for missing change logs...' && echo -en 'travis_fold:start:change\\r'
  - git fetch origin master:refs/remotes/origin/master -a
  - node common/scripts/install-run-rush.js change -v
  - echo -en 'travis_fold:end:change\\r'

  - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  - node common/scripts/install-run-rush.js update
  - echo -en 'travis_fold:end:install\\r'

  - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  - node common/scripts/install-run-rush.js build
  - echo -en 'travis_fold:end:build\\r'

  - echo 'Linting...' && echo -en 'travis_fold:start:lint\\r'
  - node common/scripts/install-run-rush.js lint
  - echo -en 'travis_fold:end:lint\\r'

  - echo 'Testing...' && echo -en 'travis_fold:start:test\\r'
  - node common/scripts/install-run-rush.js test
  - echo -en 'travis_fold:end:test\\r'

after_success:
  - echo 'Reporting...' && echo -en 'travis_fold:start:report\\r'
  - find . -maxdepth 4 -name 'lcov.info' -exec java -jar codacy-coverage-reporter-assembly.jar report -l javascript -r "{}" --partial \; && java -jar codacy-coverage-reporter-assembly.jar final
  - echo -en 'travis_fold:end:report\\r'
