# Unique identifier of the workflow which is displayed on the
# repository's action page.
name: CI

# The names of events used by GitHub to trigger the workflow.
# Workflows can use more than one webhook events for trigger.
on:
  # Trigger on push.
  push:
    branches: [master]

  # Trigger on pull request.
  pull_request:
    branches: [master]

# A map of environment variables which are available to all
# jobs and steps in the workflow by using expressions.
env:
  release: ./release

# The workflow run is made up of one or more parallel jobs.
# Jobs can be run sequentially by defining dependencies.
jobs:
  # Job to build and verify packages.
  build:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A job contains a sequence of steps.
    steps:
      # Fetch the master branch.
      - name: Checkout
        uses: actions/checkout@v2

      # Install the default Node.js.
      - name: Environment
        uses: actions/setup-node@v1

      # Verify the change file.
      - name: Change file
        run: node common/scripts/install-run-rush.js change -v
        if: github.event_name == 'pull_request'

      # Install the dependencies.
      - name: Dependencies
        run: node common/scripts/install-run-rush.js update

      # Build registered packages.
      - name: Building packages
        run: node common/scripts/install-run-rush.js build

      # Lint registered packages.
      - name: Linting packages
        run: node common/scripts/install-run-rush.js lint

      # Test registered packages.
      - name: Testing packages
        run: >-
          node common/scripts/install-run-rush.js test;
          find . -maxdepth 4 -name 'lcov.info' |
          sed -e 'H;${x;s/\n/,/g;s/^,//;p;};d' |
          xargs -I {} echo "::set-env name=COVERAGE_LCOV::{}"

      # Report test coverage.
      - name: Reporting coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}
          coverage-reports: ${{env.COVERAGE_LCOV}}

  # Job to prepare packages for release.
  prepare:
    # Depends on the success of the other job.
    needs: build

    # Run the job only on github push event.
    if: github.event_name == 'push'

    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A job contains a sequence of steps.
    steps:
      # Fetch the master branch.
      - name: Checkout
        uses: actions/checkout@v2

      # Install the default Node.js.
      - name: Environment
        uses: actions/setup-node@v1

      # Bump version and create changelog.
      - name: Version and changelog
        run: |
          git config --local user.name '${{github.workflow}}'
          git config --local user.email '${{github.workflow}}@yokize.com'

          node common/scripts/install-run-rush.js version --bump

          if ! git diff --no-ext-diff --quiet --exit-code; then
            git add .
            git commit -a -m 'ci: release'
            git push
          fi

      # Install the dependencies.
      - name: Dependencies
        run: node common/scripts/install-run-rush.js update

      # Build registered packages.
      - name: Building packages
        run: node common/scripts/install-run-rush.js build

      # Prepare packages needed for the release.
      - name: Create artifact
        env:
          package: ${{env.release}}/package
        run: >
          ls ./package | xargs -I % echo '
            mkdir -p ${{env.package}}/%;
            cp -rv ./package/%/dist/. ${{env.package}}/%;
            cp -v LICENSE ${{env.package}}/%;
            cp -v .npmignore ${{env.package}}/%;
            cp -v ./package/%/README.md ${{env.package}}/%;
            cp -v ./package/%/package.json ${{env.package}}/%;
            cp -v ./package/%/CHANGELOG.md ${{env.package}}/%;
          ' | bash

      # Upload prepared packages for the release.
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{env.release}}/**/*

  # Job to release prepared packages.
  release:
    # Depends on the success of the other job.
    needs: prepare

    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A job contains a sequence of tasks (steps).
    steps:
      # Fetch the master branch.
      - name: Checkout
        uses: actions/checkout@v2

      # Install the default Node.js.
      - name: Environment
        uses: actions/setup-node@v1

      # Download prepared packages.
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: .

      # Replace existing wih prepared packages.
      - name: Prepare packages
        run: |
          rm -r ./package
          cp -r ./artifact/. .

      # Release packages to public registry.
      - name: Release
        run: >-
          node common/scripts/install-run-rush.js publish
          --apply
          --publish
          --include-all
          --set-access-level public
          --npm-auth-token ${{secrets.NPM_AUTH_TOKEN}}
